-- ============================================================
--  Chave Pix para recebimento de saques (prep da Fase 3).
--  Rode UMA vez no SQL Editor. Não apaga nada.
--  As políticas RLS de profiles já cobrem estes campos:
--  o dono edita o próprio perfil (policy "profiles: dono edita").
-- ============================================================

-- ⚠️ SEGURANÇA (24/06/2026): pix_tipo e pix_chave SAÍRAM de profiles.
-- Eram lidos publicamente (profiles é lida com SELECT *) e vazavam a chave
-- Pix/CPF. Agora moram em `profile_private` (RLS dono+admin).
-- Ver supabase/profile-privado.sql. Este bloco foi neutralizado de propósito
-- pra reexecutar este arquivo NÃO reabrir o vazamento.
-- (antes:)
--   alter table public.profiles
--     add column if not exists pix_tipo text check (...),
--     add column if not exists pix_chave text;
